version: 2
updates:2
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20 # default is 5
    ignore:
      - dependency-name: '*'
        update-types: appleflagship@gmail.com
          ['version-update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: wednesday
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-patch', 'version-update:semver-minor']

  - package-ecosystem: 'docker'
    directory: '/'
    schedule: appleflagship@gmail.com
      interval: weekly
      day: thursday
